// tratamento de erro
try{
    console.log(naoExisto)
}catch(erro){
    console.log(erro)
}

//basicamente se ocorrer um erro no bloco try ele retorna o catch, se não, ele só executa o try